import test from 'node:test';import assert from 'node:assert/strict';
import {participants as p} from './participant-module.mjs';
import {ConnectorError,createTinkerersClient} from '../lib/tinkerers-mcp.ts';
const row={rsvp:{meetup_token:'mu_demo_event',client_token:'synthetic-1',state:'attending',checked_in:false,dietary_restrictions:'private'},client:{client_token:'synthetic-1',name:'Synthetic Example',title:'Data scientist',short_bio:'Builds speech systems. Email hidden@example.invalid or call +1 (760) 555-0100.',email:'private@example.invalid',meetup_score:99,meetup_score_eval:{assessment:'SECRET'},social_links:{url:'private'}}};
const data={filters:{meetup_token:'mu_demo_event',status:'attending'},truncated:false,next_offset:null,results:[row]};
test('participant projection drops contacts, tokens, scores, diets and unsupported fields',()=>{const out=p.participantValues(data);assert.equal(out.length,1);assert.deepEqual(Object.keys(out[0]),['display_name','title','bio','participation_status','checked_in']);assert(!/example.invalid|760|SECRET|synthetic-1|dietary|meetup_score/.test(JSON.stringify(out)));});
test('wrong-event, cancelled, duplicate and partial data fail closed',()=>{assert.throws(()=>p.participantValues({...data,truncated:true}));assert.throws(()=>p.participantValues({...data,next_offset:100}));assert.throws(()=>p.participantValues({...data,results:[row,row]}));assert.throws(()=>p.participantValues({...data,results:[{...row,rsvp:{...row.rsvp,meetup_token:'wrong'}}]}));assert.throws(()=>p.participantValues({...data,results:[{...row,rsvp:{...row.rsvp,state:'cancelled_by_user'}}]}));});
test('on-demand cache deduplicates, honors auth cooldown, and never advances stale timestamp',async()=>{let time=100000,calls=0,fail=false;const lookup=p.createParticipantLookup({now:()=>time,read:async()=>{calls++;if(fail)throw new ConnectorError('auth_expired',200000,401);return p.participantValues(data);}});const [a,b]=await Promise.all([lookup(),lookup()]);assert.equal(calls,1);assert.equal(a.live_verified,true);assert.equal(a.retrieved_at,b.retrieved_at);time+=1000;assert.equal((await lookup()).connection,'recent_cache');time+=60000;fail=true;const stale=await lookup();assert.equal(stale.live_verified,false);assert.equal(stale.retrieved_at,a.retrieved_at);time+=1000;await lookup();assert.equal(calls,2);time+=900000;const expired=await lookup();assert.equal(expired.participants.length,0);assert.equal(expired.retrieved_at,null);});
test('matching exposes evidence, no precision score, no solo or strength inference',async()=>{const d=await p.createParticipantLookup({read:async()=>p.participantValues(data)})();const voice=p.peopleForNeed(d,'Who should I introduce to someone building a voice agent?');assert.equal(voice.matches.length,1);assert(voice.matches[0].evidence.some(s=>/speech/.test(s)));assert(!('score' in voice.matches[0]));assert.equal(p.peopleForNeed(d,'Who is currently solo?').matches.length,0);assert.equal(p.peopleForNeed(d,'Who are the strongest engineers?').matches.length,0);assert.equal(p.peopleForNeed(d,'Who knows quantum computing?').matches.length,0);});
test('attendee MCP call is fixed to this event, confirmed attendance and bounded rows',async()=>{let request;const c=createTinkerersClient('synthetic',async(url,opts)=>{request=JSON.parse(opts.body);return Response.json({jsonrpc:'2.0',id:request.id,result:{structuredContent:{ok:true,data}}});});await c.read('rsvp_search');assert.deepEqual(request.params,{name:'rsvp_search',arguments:{meetup_token:'mu_demo_event',status:'attending',limit:5,offset:0}});});
test('paged reads minimize responses, discard identifiers and reject duplicate pagination',async()=>{
 const pages=[{...data,offset:0,truncated:true,next_offset:1},{...data,offset:1,results:[{rsvp:{...row.rsvp,client_token:'synthetic-2'},client:{...row.client,client_token:'synthetic-2',name:'Second Example'}}]}];
 const offsets=[];const client={initialize:async()=>{},read:async(name,offset)=>{offsets.push(offset);return pages[offset];}};
 const out=await p.retrieveParticipants(client);assert.equal(out.length,2);assert.deepEqual(offsets,[0,1]);assert(!JSON.stringify(out).includes('synthetic-'));
 await assert.rejects(()=>p.retrieveParticipants({...client,read:async(name,offset)=>offset?{...data,offset:1}:pages[0]}),/invalid_data/);
});
